### ISSUE TITLE
onReceived and onOpened bugs

### ISSUE THREAD

**Issue by donnerstag4** [geektimecoil/react-native-onesignal#293]
I tried App demo, and than success get message from onesignal when application opened notification message is showing, but when application in minimize the notification message can't show on log of onReceivedHandler or onOpenedhandler, so I can't direct to another page eg AboutPage

Thank you

**Comment by conradstrydom** [comment]
Hi. Seem to be running into a similar issue , can anyone else confirm if this is an issue?

**Comment by Jose4gg** [comment]
Yes, same here

**Comment by Alamgir** [comment]
@donnerstag4 @conradstrydom @Jose4gg maybe refer to issue #279?

**Comment by avishayil** [comment]
Please reopen this if the issue still persist.
